name: Generate Treemap

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install  # If using D3.js or other libraries

      - name: Generate Treemap
        run: npm run build-treemap  # Replace with your build command
